export const ERROR = 'ERROR'
export const STORE_UPDATED = 'STORE_UPDATED'

export const CONNECT_WALLET = 'CONNECT_WALLET'
export const CONNECT_WALLET_RETURNED = 'CONNECT_WALLET_RETURNED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_GAS_PRICE = 'GET_GAS_PRICE'
export const GAS_PRICE_RETURNED = 'GAS_PRICE_RETURNED'
